services:
  app:
    build: .
    container_name: notes-api
    ports:
      - "8080:8080"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: notesdb
      DB_USER: notesuser
      DB_PASSWORD: notespass
    depends_on:
      - db
  db:
    image: postgres:16
    container_name: notes-postgres
    restart: always
    environment:
      POSTGRES_USER: notesuser
      POSTGRES_PASSWORD: notespass
      POSTGRES_DB: notesdb
    ports:
      - "5432:5432"
    volumes:
      - ./postgresql:/docker-entrypoint-initdb.d